<a href="https://colab.research.google.com/github/joowop/Metaverse_AI_Project/blob/main/%EA%B8%8D%EB%B6%80%EC%A0%95%EB%B6%84%EC%84%9D_%EC%8A%A4%EB%85%B8%EC%9A%B0(%ED%95%84%ED%84%B0%EC%B9%B4%EB%A9%94%EB%9D%BC)_%EC%84%9C%EC%A3%BC%EC%99%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 스노우 : 필터카메라 어플

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('app_v2.csv', index_col = 0)
df.head(10)

text  score
0                                                NaN      2
1                                                NaN      5
2                                                NaN      3
3  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
4  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
5  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
6  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
7  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2
8  ●●환불요청●● 2월 초중순쯤 프리미엄 회원 무료 체험 7일 신청(무료체험기간 이후...      1
9  안녕하세요 스모우 앱 8~9년 동안 쓴 유저입니다. 그동안 진짜 잘 쓰고 있었는데 ...      1

In [3]:
df = df.iloc[3:]
df

text  score
3     그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
4     안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
5     무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
6     별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
7     쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2
...                                                 ...    ...
1998  인스타로 찍은사진을 저장하고 스노우에서 편집하려고 했는데 인스타 사진이 안뜨네요 ㅋ...      1
1999  광고 때문에 사진을 못 찍어요.. 아니 최소한 사진은 찍어야 하는데 광고가 너무 많...      1
2000  여러가지에 스티커 덕분에 한가지에 스티커가 아니어서 더욱 좋고 많이 이용하게되고 해...      5
2001  갤럭시 A90 5g기종을 쓰고 있습니다. 스노우 제가 정말 애용하는 앱인데 일반 카...      4
2002  제 핸드폰이 렉이 좀 걸리긴 한데 이 앱 들어가서 스티커를 선택하면 렉이 굉장히 심...      3

[2000 rows x 2 columns]

In [4]:
# 인덱스 새로 생성하기
df.reset_index(inplace = True)
df.head(10)

index                                               text  score
0      3  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
1      4  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
2      5  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
3      6  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
4      7  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2
5      8  ●●환불요청●● 2월 초중순쯤 프리미엄 회원 무료 체험 7일 신청(무료체험기간 이후...      1
6      9  안녕하세요 스모우 앱 8~9년 동안 쓴 유저입니다. 그동안 진짜 잘 쓰고 있었는데 ...      1
7     10  너~무좋아요 장점도 많고 단점도 조금있는것갇아요 우선 장점은요 색깔과 동영상이 너무...      4
8     11  스노우 저도 AI 프로필 한번 해보고 싶어서 결제까지 다하고선 너무 급증으로 작업 ...      2
9     12  정말 유용하개 잘 사용하고 있었는데 오늘보니 어플이 업데이트 되었더라구요. 기존 잘...      4

In [5]:
df.drop(['index'], axis = 1, inplace = True)

<ipython-input-5-271fdff9e6ab>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['index'], axis = 1, inplace = True)


In [6]:
df.head()

text  score
0  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
1  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
2  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
3  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
4  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2

In [7]:
# 똑같은 댓글 (중복 데이터) 제거
df = df.drop_duplicates(subset=['text'])
df

text  score
0     그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
1     안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
2     무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
3     별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
4     쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2
...                                                 ...    ...
1995  인스타로 찍은사진을 저장하고 스노우에서 편집하려고 했는데 인스타 사진이 안뜨네요 ㅋ...      1
1996  광고 때문에 사진을 못 찍어요.. 아니 최소한 사진은 찍어야 하는데 광고가 너무 많...      1
1997  여러가지에 스티커 덕분에 한가지에 스티커가 아니어서 더욱 좋고 많이 이용하게되고 해...      5
1998  갤럭시 A90 5g기종을 쓰고 있습니다. 스노우 제가 정말 애용하는 앱인데 일반 카...      4
1999  제 핸드폰이 렉이 좀 걸리긴 한데 이 앱 들어가서 스티커를 선택하면 렉이 굉장히 심...      3

[1999 rows x 2 columns]

In [8]:
df.isnull().sum()

text     0
score    0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1999 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    1999 non-null   object
 1   score   1999 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 46.9+ KB


In [10]:
# !pip install konlpy

In [11]:
from konlpy.tag import Okt
from collections import Counter

In [12]:
# 단어 사전 만들기 : 파싱 (말뭉치를 만들어야한다.) text에 있는 문장들을 하나로 만들면 된다.
text_data = ''.join(list(df['text']))
text_data

'그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도 하얗게 찍히더라구요. 볼터치가 과하게 하얗게 된것처럼. 필터를 다 바꿔봐도 전혀 나아지지 않아서 안쓰고 있다가 오늘 오랫만에 수업시간에 사진찍을 일이 있어서 앱을 키고 사진을 찍었습니다. 찰칵소리가 나지 않아 수업시간에 사용한거였는데 사진찍고는 저장이 안되고 바로 결제화면으로 넘어가네요. 이럴줄 알았음 그냥 일반카메라로 찍을걸 수업에 방해될까봐 스노우로 찍은거였는데 다시 찍을수도 없고 결국 무료체험 눌러서 사진 저장하고 다시 구독취소하고 리뷰쓰러 왔습니다. 이제 앱지우러 가려구요. 그동안 잘썼습니다.안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸렸다가 카메라를 사용할수없다뜨고 저장이 안되네요. (안되는 경우가 더 많고, 정말 가끔 저장됩니다.) 폰껐다 켜봤고, 스노우 어플 삭제했다 깔아봤습니다. 폰기종은 갤s22고요, 후면카메라는 저장됩니다. vip한 이유가 vip필터 및 고화질로 셀카찍으려 한건데 안되니 답답하네요 ㅜ 해결 부탁드립니다..무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 본 계정으로 결제 된 것이 맞는지 확인하고 취소 하세요. 저도 결제수단에 따라 원래 플레이스토어 로그인 계정이 아닌 다른 구글계정으로 결제가 되어있더라구요 그 계정으로 로그인하신 후 환불 요청하시면 될수도 있습니다 원래부터 잘써오던 어플인데 발전하고는 있으나 카메라화질, 갑작스런 광고, 기타 등등 오류가 너무 많아서 아쉽습니다. 보정 어플 중에 자연스럽고 화질이 깨지지않아서 가장 애용했는데 일부는 유료전환되고 터치보정은 리뉴얼된게 더 불편한 것 같아요.별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼고 정말 엉망입니다. 아무리 사용자가 급증했고, 그로인한 오류도 증가한다면 이용자수에 한해서 뭐 대책을 세워야 하는거 아닌가요? 공짜로 하는것도 아니고 값을 지불하는건데, 이건 해도 너무하네요. 

In [13]:
okt = Okt()
nouns = okt.nouns(text_data)
print(nouns)

['그동안', '개', '날인', '부터', '사진', '볼', '부분', '볼터치', '과', '필터', '전혀', '오늘', '만', '수업', '시간', '사진', '찍', '앱', '키', '사진', '소리', '수업', '시간', '사용', '거', '사진', '저장', '바로', '결제', '화면', '그냥', '카메라', '수업', '방해', '스노우', '다시', '무료', '체험', '사진', '저장', '다시', '구독', '취소', '리뷰', '이제', '앱', '그동안', '주전', '셀카', '모드', '고화질', '로', '촬영', '렉', '잠깐', '카메라', '사용', '저장', '경우', '더', '정말', '가끔', '저장', '폰', '켜', '스노우', '어플', '삭제', '폰', '기종은', '고요', '후', '카메라', '저장', '이유', '필터', '및', '고화질', '셀카', '해결', '무료', '체험', '후', '구독', '취소', '애', '분', '로', '온', '결제', '역', '알림', '계정', '결제', '것', '확인', '취소', '저', '결제', '수단', '원래', '플레이스토어', '로그인', '계정', '다른', '구글', '계정', '결제', '그', '계정', '로그인', '후', '환불', '요청', '원래', '어플', '발전', '카메라', '화질', '광고', '기타', '등등', '오류', '보정', '어플', '중', '화질', '가장', '애용', '일부', '유료', '전환', '터치', '보정', '리뉴얼', '더', '것', '별', '단', '개도', '주기', '어플', '요', '스노우', '꽤', '번', '결제', '처음', '정말', '엉망', '사용자', '급증', '그로', '오류', '증가', '이용', '자수', '한해', '뭐', '대책', '공짜', '값', '지불', '이건', '해도', '남자', '백원', '결제', '대부분', 

In [14]:
# 빈도수 체크
counter = Counter(nouns)
print(counter)

Counter({'사진': 1192, '스노우': 737, '스티커': 636, '앱': 607, '저장': 542, '필터': 541, '때': 517, '사용': 512, '기능': 404, '제': 389, '보정': 388, '것': 372, '다시': 367, '결제': 336, '카메라': 316, '좀': 302, '어플': 301, '이': 298, '왜': 289, '정말': 284, '거': 272, '업데이트': 262, '광고': 259, '수': 255, '점': 252, '진짜': 247, '안': 234, '계속': 220, '화면': 208, '찍': 200, '폰': 200, '저': 197, '얼굴': 197, '편집': 192, '동영상': 188, '전': 186, '렉': 184, '환불': 183, '후': 182, '오류': 181, '요': 173, '더': 169, '개': 167, '다른': 166, '촬영': 165, '그': 164, '갑자기': 153, '셀카': 143, '설정': 138, '영상': 133, '별': 132, '버튼': 131, '적용': 126, '문제': 125, '번': 117, '삭제': 115, '또': 114, '사람': 114, '자동': 107, '하나': 107, '프로필': 106, '아바타': 101, '돈': 100, '수정': 98, '개선': 96, '친구': 95, '한번': 93, '그냥': 92, '추천': 92, '폴더': 91, '확인': 88, '소리': 87, '해결': 86, '지금': 86, '화질': 85, '핸드폰': 85, '갤럭시': 85, '시간': 84, '뭐': 84, '제발': 84, '메이크업': 84, '자꾸': 83, '부분': 82, '못': 82, '가요': 82, '바로': 81, '말': 81, '예전': 81, '정도': 81, '꼭': 81, '때문': 80, '원래': 77, '걸': 75, '조금': 75, '유저'

In [15]:
noun_data = Counter({x:counter[x] for x in counter if len(x) > 1})
noun_data.most_common(10)

[('사진', 1192),
 ('스노우', 737),
 ('스티커', 636),
 ('저장', 542),
 ('필터', 541),
 ('사용', 512),
 ('기능', 404),
 ('보정', 388),
 ('다시', 367),
 ('결제', 336)]

In [16]:
# 벡터화
import re
from tqdm import tqdm

noun_result = [] # [ [], [], [] ]

for temp in tqdm(df['text']):
    han = re.compile('[^ㄱ-ㅣ가-힣]') # 정규표현식
    temp_result = han.sub(' ', temp) # 문장에서 한글만 남기고 제거
    temp_noun = okt.nouns(temp_result)
    result_noun = [x for x in temp_noun if len(x) > 1] # 각 댓글을 명사 단위로 쪼갠뒤 한글자 이상인것만 저장
    noun_result.append(result_noun)

print(noun_result)

100%|██████████| 1999/1999 [00:19<00:00, 100.63it/s]

[['그동안', '날인', '부터', '사진', '부분', '볼터치', '필터', '전혀', '오늘', '수업', '시간', '사진', '사진', '소리', '수업', '시간', '사용', '사진', '저장', '바로', '결제', '화면', '그냥', '카메라', '수업', '방해', '스노우', '다시', '무료', '체험', '사진', '저장', '다시', '구독', '취소', '리뷰', '이제', '그동안'], ['주전', '셀카', '모드', '고화질', '촬영', '잠깐', '카메라', '사용', '저장', '경우', '정말', '가끔', '저장', '스노우', '어플', '삭제', '기종은', '고요', '카메라', '저장', '이유', '필터', '고화질', '셀카', '해결'], ['무료', '체험', '구독', '취소', '결제', '알림', '계정', '결제', '확인', '취소', '결제', '수단', '원래', '플레이스토어', '로그인', '계정', '다른', '구글', '계정', '결제', '계정', '로그인', '환불', '요청', '원래', '어플', '발전', '카메라', '화질', '광고', '기타', '등등', '오류', '보정', '어플', '화질', '가장', '애용', '일부', '유료', '전환', '터치', '보정', '리뉴얼'], ['개도', '주기', '어플', '스노우', '결제', '처음', '정말', '엉망', '사용자', '급증', '그로', '오류', '증가', '이용', '자수', '한해', '대책', '공짜', '지불', '이건', '해도', '남자', '백원', '결제', '대부분', '엉망', '머리', '여성', '처리', '사진', '쭈글쭈글', '환불'], ['광고', '기본', '무료', '광고', '이해', '얼마', '고량', '방금', '사진', '보정', '저장', '광고', '매번', '사진', '광고', '필름', '필카', '디카', '즉시', '사진', '식이', '된거'],

In [17]:
# 글자를 숫자로 바꿔버리기 (bag of word 벡터 생성 )
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(tokenizer = lambda x : x, lowercase = False)
bow_vect = count_vectorizer.fit_transform(noun_result)
word_list = count_vectorizer.get_feature_names_out()
print(word_list)
len(word_list)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


['가게' '가격' '가기' ... '히트' '힐링' '힝구']


3017

In [18]:
bow_vect.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
len(bow_vect.toarray()[0])

3017

In [20]:
# 단어별 전체 등장 횟수
count_list = bow_vect.toarray().sum(axis=0)
count_list

array([ 1,  5, 10, ...,  1,  1,  1])

In [21]:
word_count = dict(zip(word_list, count_list))
word_count

{'가게': 1,
 '가격': 5,
 '가기': 10,
 '가까이': 7,
 '가끔': 52,
 '가나': 5,
 '가능': 8,
 '가능성': 1,
 '가다가': 1,
 '가도': 1,
 '가두': 1,
 '가득': 1,
 '가라': 1,
 '가락': 1,
 '가량': 2,
 '가로': 7,
 '가름': 1,
 '가면': 6,
 '가문': 1,
 '가발': 1,
 '가보': 1,
 '가상': 1,
 '가시': 1,
 '가안': 2,
 '가야': 3,
 '가요': 82,
 '가용': 2,
 '가운데': 7,
 '가을': 3,
 '가입': 3,
 '가장': 20,
 '가장자리': 1,
 '가족': 10,
 '가지': 37,
 '가지각색': 1,
 '가짐': 2,
 '가짜': 2,
 '가해': 4,
 '각각': 3,
 '각도': 2,
 '각자': 2,
 '각종': 2,
 '간곡': 1,
 '간다': 1,
 '간만': 1,
 '간의': 1,
 '간전': 1,
 '간직': 1,
 '간혹': 2,
 '갇다대': 1,
 '갈색': 1,
 '갈수': 1,
 '갈수록': 10,
 '감기': 1,
 '감동': 4,
 '감사': 2,
 '감성': 2,
 '감지': 1,
 '감탄': 2,
 '갑자': 1,
 '갑자기': 153,
 '강당': 1,
 '강도': 5,
 '강력': 6,
 '강아지': 19,
 '강의': 2,
 '강점': 2,
 '강제': 8,
 '강조': 1,
 '강종': 3,
 '강추': 36,
 '강화': 1,
 '같아얍': 1,
 '같아욤': 2,
 '개개인': 2,
 '개념': 1,
 '개도': 11,
 '개돼지': 1,
 '개드립': 3,
 '개발': 9,
 '개발자': 25,
 '개별': 8,
 '개불': 1,
 '개뿔': 1,
 '개선': 96,
 '개성': 1,
 '개열': 2,
 '개월': 5,
 '개월치': 1,
 '개인': 18,
 '개인정보': 5,
 '개일때': 1,
 '개임': 1,
 '개정': 2,
 '개중': 1,
 '개진': 1,
 '개

In [22]:
# tf-idf 생성
from sklearn.feature_extraction.text import TfidfTransformer

tf_vectorizer = TfidfTransformer()
tf_idf = tf_vectorizer.fit_transform(bow_vect)
tf_idf.toarray() # 각각 단어의 가중치가 담겨져있는 tridf가 만들어진다. (학습 데이터 생성 완료)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
df.head()

text  score
0  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2
1  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5
2  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3
3  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1
4  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2

In [24]:
# score가 4점부터는 긍정(1)으로 4점미만은 부정(0)으로 label로 설정할것이다.
df['score_real'] = np.where(df['score'] >= 4, 1, 0)
df.head()

<ipython-input-24-61e7fefcea65>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['score_real'] = np.where(df['score'] >= 4, 1, 0)


text  score  score_real
0  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2           0
1  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5           1
2  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3           0
3  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1           0
4  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2           0

In [25]:
df['score_real'].value_counts() # 부정적인게 더 많다

0    1132
1     867
Name: score_real, dtype: int64

In [26]:
df.head(10)

text  score  score_real
0  그동안은 잘썼으니 별두개 드립니다. 어느날인가부터 사진을 찍으면 볼 부분만 너무나도...      2           0
1  안녕하세요, 잘쓰고 있긴한데 한 몇주전부터 셀카모드(고화질)로 촬영하면 렉 잠깐 걸...      5           1
2  무료 체험 후 구독 취소에 애먹으시고 계신 분들은 gmail로 온 결제내역 알림에 ...      3           0
3  별을 단 1개도 주기 아까운 어플이네요. 스노우 꽤 여러번 결제를 했구요. 처음 빼...      1           0
4  쓰면 쓸수록 광고가 많아지는 신기한 앱입니다. 물론 기본이 무료앱이니까 광고 보는거...      2           0
5  ●●환불요청●● 2월 초중순쯤 프리미엄 회원 무료 체험 7일 신청(무료체험기간 이후...      1           0
6  안녕하세요 스모우 앱 8~9년 동안 쓴 유저입니다. 그동안 진짜 잘 쓰고 있었는데 ...      1           0
7  너~무좋아요 장점도 많고 단점도 조금있는것갇아요 우선 장점은요 색깔과 동영상이 너무...      4           1
8  스노우 저도 AI 프로필 한번 해보고 싶어서 결제까지 다하고선 너무 급증으로 작업 ...      2           0
9  정말 유용하개 잘 사용하고 있었는데 오늘보니 어플이 업데이트 되었더라구요. 기존 잘...      4           1

In [27]:
from sklearn.model_selection import train_test_split

x = tf_idf
y = df['score_real']

# 긍정과 부정 중에 부정이 많기 때문에 두가지의 비율을 맞춰주기 위해서 stratify를 쓴다.
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1, stratify = df['score_real'])

In [28]:
print(X_train.shape)
print(X_test.shape)

(1399, 3017)
(600, 3017)


In [29]:
# 모델 학습 이진분류
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score

lr_model = LogisticRegression(random_state=1)
lr_model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [30]:
y_pred = lr_model.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [31]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)


print("Accuracy:", accuracy)
print("Precision:", precision)



Accuracy: 0.7583333333333333
Precision: 0.7699530516431925


In [32]:
invert_index_vectorizer = {v:k for k, v in count_vectorizer.vocabulary_.items()}
invert_index_vectorizer

{304: '그동안',
 417: '날인',
 1154: '부터',
 1263: '사진',
 1147: '부분',
 1138: '볼터치',
 2822: '필터',
 2240: '전혀',
 1819: '오늘',
 1417: '수업',
 1481: '시간',
 1381: '소리',
 1254: '사용',
 2211: '저장',
 980: '바로',
 169: '결제',
 2957: '화면',
 300: '그냥',
 2588: '카메라',
 1032: '방해',
 1440: '스노우',
 510: '다시',
 913: '무료',
 2507: '체험',
 269: '구독',
 2566: '취소',
 763: '리뷰',
 2039: '이제',
 2360: '주전',
 1368: '셀카',
 883: '모드',
 219: '고화질',
 2538: '촬영',
 2158: '잠깐',
 175: '경우',
 2262: '정말',
 4: '가끔',
 1695: '어플',
 1270: '삭제',
 358: '기종은',
 209: '고요',
 2033: '이유',
 2889: '해결',
 1622: '알림',
 187: '계정',
 2970: '확인',
 1407: '수단',
 1916: '원래',
 2805: '플레이스토어',
 735: '로그인',
 501: '다른',
 265: '구글',
 2974: '환불',
 1886: '요청',
 1020: '발전',
 2967: '화질',
 253: '광고',
 361: '기타',
 668: '등등',
 1827: '오류',
 1115: '보정',
 30: '가장',
 1634: '애용',
 2087: '일부',
 1944: '유료',
 2243: '전환',
 2665: '터치',
 756: '리뉴얼',
 76: '개도',
 2345: '주기',
 2488: '처음',
 1737: '엉망',
 1255: '사용자',
 333: '급증',
 309: '그로',
 2389: '증가',
 2028: '이용',
 2133: '자수',
 287

In [33]:
# 긍정적인 리뷰를 만드는데 사용된 단어들 찾기 reverse=True , False로 바꾸면 부정적 단어를 볼수 있다.
from sqlalchemy import true
coef_pos_index = sorted(((value,index) for index,value in enumerate(lr_model.coef_[0])),reverse=True)
for coef in coef_pos_index[:20]:
    print(invert_index_vectorizer[coef[1]], coef[0])

추천 1.8497048077168012
단점 1.7308264182776971
화장 1.6022424840039975
최고 1.5337925068461447
친구 1.498140934705201
혹시 1.370517646865746
조금 1.312145971619209
완전 1.2485828945789763
그게 1.1810087789463464
메이크업 1.1589254172245327
아주 1.1063948170891864
셀카 1.0945237749213508
스노우 1.0872494840303522
강추 1.086807911428042
음악 1.0563871187287377
추가 1.042597285944009
장점 1.0306721365415241
한가지 0.9391186819760706
등등 0.9226433393977509
게임 0.9109423693593213


In [34]:
def comment_predict(text):
    sentence_test = text
    han = re.compile('[^ㄱ-ㅣ가-힣]')
    temp_result = han.sub(' ', sentence_test)
    temp_noun = okt.nouns(temp_result)
    result_noun = [x for x in temp_noun if len(x) > 1]
    vec_test = count_vectorizer.transform([result_noun])
    vec_test.toarray().sum()
    tf_test = tf_vectorizer.transform(vec_test)
    tf_test.toarray().sum()

    result = ''
    if lr_model.predict(tf_test)[0] == 1:
        result = '긍정'
    else:
        result = '부정'
    return result

In [35]:
comment_predict('셀카를 찍으면 피부 보정이 잘 되서 나오네요')

'긍정'

In [36]:
comment_predict('광고가 너무 많이 나와요')

'부정'

In [37]:
comment_predict('엉망이네요')

'부정'

In [38]:
comment_predict('필터 좋네요')

'긍정'